### ISSUE TITLE
Xinfrared T2 Pro

### ISSUE THREAD

**Issue by AbbosAbdullayev** [LeoDJ/P2Pro-Viewer#16]

**Comment by AbbosAbdullayev** [comment]
is it working on the Xinfrared T2 Pro camera?

**Comment by LeoDJ** [comment]
No, sorry.
But you can look here: https://www.eevblog.com/forum/thermal-imaging/thermal-imaging-windows-application-for-infiray-t2-t3-thermal-cameras/
