### ISSUE TITLE
Infiray types

### ISSUE THREAD

**Issue by mhmdajami** [LeoDJ/P2Pro-Viewer#6]
hello,
well done on this project @LeoDJ.
I'm trying to work with 2 modules xcore micro 3 lite, but I'm trying to customize a Python code for specific requirements.
does this code work with my modules? does it read two cameras at the same time? also if this code can open an irv video recorded files.
thank you very much.
hope i hear from you soon.
Ajami

**Comment by LeoDJ** [comment]
The only module I think might be similar to the P2 Pro would be the Tiny1-B module.
And my tool is currently pretty unfinished, I didn't have the time the last few months to work on it.

From the specs of the InfiRay Micro III Lite 640 module, it looks to be quite another type of product. The video interface isn't simply USB or SPI, but rather LVDS/MIPI/BT.656/CDS2 (more complicated).

I'm afraid my tool wouldn't help you with that either, even if it would be working ^^"
But I wish you much success for your project, sounds cool!
