### ISSUE TITLE
Share picture of driver setup?

### ISSUE THREAD

**Issue by rapzak** [LeoDJ/P2Pro-Viewer#7]
Hi,

I am trying to use your code for a T2S+ cam - but i have some issues to install the filter driver / use it, will it come up in device manager?

How does it look when it is correct?

Thanks

**Comment by LeoDJ** [comment]
Afaik, the T2S+ camera uses a different protocol compared to the P2 Pro, I'd suggest checking out the software from RuneHansen:  
https://www.eevblog.com/forum/thermal-imaging/thermal-imaging-windows-application-for-infiray-t2-t3-thermal-cameras/
