### ISSUE TITLE
P2 Support ?

### ISSUE THREAD

**Issue by bordins** [LeoDJ/P2Pro-Viewer#8]
Hi,

I wonder the code can be used with the P2.  I happen to have one.

Thank you.

**Comment by LeoDJ** [comment]
Afaik, the only difference between the two is the lack of a high temperature mode on the normal P2. So the chances are pretty good, but I don't have one to test it with.  

My tool is currently in a pre-alpha state and not really usable yet.  
But if you have a P2, you could try the basic viewer from Les: https://github.com/leswright1977/PyThermalCamera  
(The TC001 is basically identical to the P2 Pro)
